import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "./components/Header";
import { cn } from "./lib/utils";
import { Providers } from "./providers";

// const inter = Inter({ subsets: ['latin'] })
const myFont = localFont({ src: "../public/font/conthrax-sb.otf" });

export const metadata: Metadata = {
  title: "Crosslink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(myFont.className, "flex flex-col items-center black")}
      >
        <Providers>
          <main>
            <div className="flex flex-col justify-between min-h-screen relative w-full max-w-7xl px-4 mx-auto">
              <Header />
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
